<?php

declare(strict_types=1);

namespace Liberu\Genealogy\Dna\Services;

final class DnaFileValidator
{
    public const MAX_BYTES = 104_857_600;

    /** @return array{valid: bool, format: string|null, snp_count: int, error: string|null} */
    public function validate(string $content): array
    {
        $size = strlen($content);
        if ($size < 1024) {
            return $this->invalid('File is too small to be a valid DNA file.');
        }
        if ($size > self::MAX_BYTES) {
            return $this->invalid('File exceeds the maximum supported size.');
        }

        $lines = preg_split('/\R/', $content, 3) ?: [];
        $first = $lines[0] ?? '';
        $second = $lines[1] ?? '';
        $format = $this->detectFormat($first, $second);
        if ($format === null) {
            return $this->invalid('Unrecognized DNA file format.');
        }

        $snpCount = 0;
        foreach (preg_split('/\R/', $content) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }
            if (preg_match('/^rs\d+[\s,\t]/i', $line) === 1) {
                $snpCount++;
            }
        }

        return ['valid' => true, 'format' => $format, 'snp_count' => $snpCount, 'error' => null];
    }

    public function detectFormat(string $firstLine, string $secondLine = ''): ?string
    {
        $header = strtolower($firstLine.' '.$secondLine);
        if (str_contains($header, '# this data file generated by 23andme')) {
            return '23andme';
        }
        if (str_contains($firstLine, 'rsid') && str_contains($firstLine, 'chromosome')) {
            return 'ancestry';
        }
        if (str_contains($firstLine, 'RSID') && str_contains($firstLine, 'Chr')) {
            return 'myheritage';
        }
        if (str_contains($firstLine, 'RSID') && str_contains($firstLine, 'CHROMOSOME')) {
            return 'ftdna';
        }

        return preg_match('/rs\d+/i', $header) === 1 ? 'generic' : null;
    }

    /** @return array{valid: false, format: null, snp_count: 0, error: string} */
    private function invalid(string $error): array
    {
        return ['valid' => false, 'format' => null, 'snp_count' => 0, 'error' => $error];
    }
}
