<?php

declare(strict_types=1);

namespace Liberu\Genealogy\Dna\Services;

/**
 * Converts supported consumer DNA exports into the map consumed by the matcher.
 * Raw content is processed in memory and is never written by this service.
 */
final class ParseDnaFile
{
    /** @var array<string, string> */
    private const CHROMOSOME_ALIASES = ['23' => 'X', '24' => 'Y', '26' => 'MT', 'M' => 'MT'];

    /** @var list<string> */
    private const VALID_CHROMOSOMES = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT'];

    /** @return array<string, array<int, string>> */
    public function parse(string $content): array
    {
        $format = null;
        $comments = '';
        $map = [];

        foreach (preg_split('/\R/', $content) ?: [] as $rawLine) {
            $line = trim($rawLine);
            if ($line === '') {
                continue;
            }

            if ($line[0] === '#') {
                $comments .= $line."\n";

                continue;
            }

            $delimiter = str_contains($line, "\t") ? "\t" : ',';
            $fields = array_map('trim', str_getcsv($line, $delimiter, '"', ''));
            $format ??= $this->detectFormat($comments, $line);

            if (strcasecmp($fields[0] ?? '', 'rsid') === 0 || count($fields) < 4) {
                continue;
            }

            $chromosome = $this->normalizeChromosome($fields[1] ?? '');
            if ($chromosome === null || ! ctype_digit($fields[2] ?? '')) {
                continue;
            }

            $genotype = ($format === 'ancestry' && isset($fields[4]))
                ? ($fields[3].$fields[4])
                : ($fields[3] ?? '');
            $genotype = $this->normalizeGenotype($genotype);
            if ($genotype === null) {
                continue;
            }

            $map[$chromosome][(int) $fields[2]] = $genotype;
        }

        return $map;
    }

    private function detectFormat(string $comments, string $header): string
    {
        if (str_contains($comments, 'This data file generated by 23andMe')) {
            return '23andme';
        }

        if (str_contains($header, 'rsid') && str_contains($header, 'chromosome')) {
            return 'ancestry';
        }

        if (str_contains($header, 'RSID') && str_contains($header, 'Chr')) {
            return 'myheritage';
        }

        if (str_contains($header, 'RSID') && str_contains($header, 'CHROMOSOME')) {
            return 'ftdna';
        }

        return 'generic';
    }

    private function normalizeChromosome(string $value): ?string
    {
        $chromosome = strtoupper(trim($value));
        if (str_starts_with($chromosome, 'CHR')) {
            $chromosome = substr($chromosome, 3);
        }

        $chromosome = self::CHROMOSOME_ALIASES[$chromosome] ?? $chromosome;

        return in_array($chromosome, self::VALID_CHROMOSOMES, true) ? $chromosome : null;
    }

    private function normalizeGenotype(string $value): ?string
    {
        $genotype = strtoupper(trim($value));
        if (strlen($genotype) === 1) {
            $genotype .= $genotype;
        }

        if (! preg_match('/^[ACGT]{2}$/', $genotype)) {
            return null;
        }

        return $genotype[0] <= $genotype[1]
            ? $genotype
            : $genotype[1].$genotype[0];
    }
}
